"""
Every config field, documented once. A dataset config does
`from src.configs.base import *` and overrides whatever it needs — fields
below with empty/placeholder values (DATA_PATH, FEATURES, etc.) MUST be
overridden per dataset; the rest have sensible defaults and only need
overriding when tuning calls for it. This keeps documentation in one
place instead of repeated across every dataset config file.
"""

# --- Dataset-specific — must be overridden, these have no sensible default ---

# Path to the source CSV, relative to the project root.
DATA_PATH = ""

# Link to where the dataset came from — included in the auto-generated
# report so provenance travels with the results.
DATA_SOURCE_URL = ""

# Non-feature columns to drop before modeling (e.g. row IDs).
ID_COLUMNS = []

# Categorical/target column kept for reference but excluded from generation
# (the generators here only model continuous features).
LABEL_COLUMN = ""

# The continuous columns every generator models.
FEATURES = []

# Root variables for the physics-informed Monte Carlo generator: no parent
# in the causal graph, sampled directly from their own real marginal
# distribution.
ROOT_VARIABLES = []

# Assumed causal chain: each (parent, child) edge means `child` is generated
# from parent's fitted linear relationship plus calibrated residual noise.
# This is the one piece of real domain knowledge in the pipeline. Every
# parent must appear in ROOT_VARIABLES or as a child earlier in this list.
CAUSAL_GRAPH = []

# Categorical column to use for the leave-one-group-out transfer experiment
# (make loro). Each value is held out in turn, its population generated by a
# conditional-VAE ensemble trained on the others, and fidelity + epistemic
# uncertainty measured near vs far (see src.evaluation.loro). Empty = no LORO
# for this dataset. The column may also be one of FEATURES; it's used as the
# condition and excluded from the modeled features during the experiment.
LORO_GROUP = ""

# Whether FEATURES in the source CSV are already standardized (mean 0,
# std 1). If True, main.py feeds the VAE raw values as-is and skips
# inverse-transforming its output (there's no original unscaled space to
# return to). If False, main.py fits its own StandardScaler for the VAE
# and inverse-transforms generated samples back to the source units.
IS_PRE_SCALED = False

# --- Pipeline mechanics — sensible defaults, override only if tuning calls for it ---

# Fraction of the data held out as the "real" individuals every metric is scored
# against. Never used for fitting, calibration, or causal-edge estimation.
TEST_SIZE = 0.3

# Whether to run the Train-on-Synthetic/Test-on-Real downstream-utility check
# (src.evaluation.tstr). Runs only when LABEL_COLUMN is also set and the label
# has >=2 classes; auto-skips otherwise. It re-generates each label class
# separately per engine, so it adds generation cost on top of the main run —
# set False on a dataset where the label is degenerate (e.g. a deterministic
# bucket of a feature) or where the extra cost isn't wanted.
RUN_TSTR = True

# How many synthetic rows each generator produces, independent of dataset size.
N_SAMPLES = 1000

RANDOM_SEED = 48

# VAE latent dimensionality — a reasonable starting point; tune per dataset
# if the causal structure has more independent noise sources than this.
LATENT_DIM = 4

# VAE training epochs and final KL weight (beta) — beta is linearly annealed
# up to this value over training (see vae_generator.generate) to avoid
# posterior collapse. Training stops early if the loss hasn't improved for
# VAE_PATIENCE epochs (checked only after KL warmup finishes), so VAE_EPOCHS
# can be set as a generous upper bound rather than hand-tuned per run.
VAE_EPOCHS = 5000
VAE_BETA = 1.0
VAE_PATIENCE = 400

# Hidden layer width for the VAE's encoder/decoder, and dropout probability
# inside them (0.0 disables dropout). The default width is tuned for
# apple_quality's 2800 rows; on a much smaller dataset that many parameters
# can memorize training noise instead of generalizing — shrink VAE_HIDDEN_DIM
# and/or add VAE_DROPOUT if the generalization check shows a large train/test
# gap (see vae_generator.generate).
VAE_HIDDEN_DIM = 128
VAE_DROPOUT = 0.0

# Floor on KL cost per latent dimension (in nats) — 0.0 disables it (a valid
# per-dim KL is already >= 0, so a zero floor is a no-op). The
# posterior-collapse signature to watch for is recon_loss plateauing at ~1.0 on
# standardized data (no better than always predicting the mean) with KL near
# zero; 0.5-2.0 addresses it. An unneeded floor wastes model capacity.
VAE_FREE_BITS = 0.0

# Weight on the covariance-matching loss term: penalizes the squared
# difference between the reconstructed batch's covariance matrix and the
# real batch's. Gives the model direct pressure toward preserving feature
# correlations, which the reconstruction+KL ELBO alone doesn't reward.
VAE_COV_WEIGHT = 1.0

# Weight on the physics-consistency loss term, used only by the
# physics-informed VAE (hybrid_vae_generator). Penalizes reconstructed
# batches that violate the fitted linear-Gaussian relationship on each
# CAUSAL_GRAPH edge — matching its slope, intercept, and real residual
# spread — so the VAE is pushed onto the same mechanism the physics-informed
# Monte Carlo generator samples, without collapsing feature variance. Set to
# 0.0 to make the physics-informed VAE behave identically to the plain VAE.
VAE_PHYSICS_WEIGHT = 1.0

# Weight on the marginal-matching loss term, used only by the
# physics-informed VAE. The per-feature 1D Wasserstein distance between
# samples drawn from the prior and the real batch — the differentiable
# analogue of the KS statistic. The physics term constrains only causal
# edges, so the graph's root variables (which physics-MC samples directly
# from their real marginal) tend to get compressed by the VAE; this term
# shapes every generated feature's full distribution onto real, roots
# included. Set to 0.0 to disable.
VAE_MARGINAL_WEIGHT = 1.0

# Physics-informed VAE — whether the covariance and physics constraints
# are applied to freshly generated rows (True) or to reconstructions of real
# inputs (False). Constraining the generated population directly optimizes the
# joint structure of what is actually sampled at generation, which lowers
# correlation distance at no cost to marginal fit, spread, or the train/test gap.
VAE_CONSTRAIN_GENERATED = True

# Physics-informed VAE — latent sampling at generation. "standard" draws
# from the N(0, I) prior; "aggregate" draws from the aggregate posterior over the
# training rows, which overfits the training encodings and widens the train/test
# gap without improving fidelity, so "standard" is the default.
VAE_PRIOR_TYPE = "standard"

# Physics-informed VAE — empirical-copula marginal calibration. After
# generation, maps each feature onto the real training marginal at matching
# quantiles (see hybrid_vae_generator._calibrate_marginals): the VAE supplies the
# dependence structure and the margins come from the real empirical distribution.
# It improves marginal fit and per-feature spread and keeps values physically
# valid. A calibrated run is "learned dependence + real margins" rather than
# purely learned, which is reported as such.
VAE_CALIBRATE_MARGINALS = True

# When calibration is on, also report a second, uncalibrated PI-VAE variant
# ("hybrid_vae_raw") alongside it in the main comparison. The calibration
# post-step is a monotonic per-feature remap onto the real margins, so it
# preserves rank (Spearman) correlation but not Pearson, which is what
# correlation_euclidean_dist measures. On near-symmetric features the two agree
# and calibration costs nothing; on heavily skewed features the remap perturbs
# the Pearson correlation, so the calibrated PI-VAE can trail on correlation
# while still leading on marginal fit and calibration. Enabling this trains the
# same model twice with a fixed seed and toggles only the post-step, making the
# two rows an ablation of that trade-off. Ignored when
# VAE_CALIBRATE_MARGINALS is False.
VAE_REPORT_UNCALIBRATED = False

# Whether to train in shuffled mini-batches (adds stochastic noise to escape
# flat/plateaued loss regions) vs. one full-batch gradient step per epoch.
# Disable for very small datasets where mini-batches would just add noise
# without enough data per batch to estimate a stable gradient.
VAE_USE_MINIBATCH = False
VAE_BATCH_SIZE = 128
